[package]
name = "tauri-app"
version = "0.1.0"
description = "A Tauri App"
authors = [ "you" ]
license = ""
repository = ""
default-run = "tauri-app"
edition = "2018"
build = "src/build.rs"

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = [ "derive" ] }
tauri = { path = "C:\\Aivan\\PE\\tauri\\tauri", features =["api-all"]}

[target."cfg(windows)".build-dependencies]
winres = "0.1"

[features]
custom-protocol = [ "tauri/custom-protocol" ]

[[bin]]
name = "tauri-app"
path = "src/main.rs"
